sonar.organization=arrase
sonar.projectKey=arrase_code-reducer
sonar.projectName=code-reducer
sonar.sourceEncoding=UTF-8

# Source and Test configuration
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/wiki/**,**/dist/**,**/site/**,**/examples/**,**/screenshots/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Go Coverage
sonar.go.coverage.reportPaths=coverage.out
